version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
before_build:
- cmd: >-
    nuget restore

    nuget install glTF2Loader -PreRelease -Version 1.1.1-alpha -OutputDirectory C:\projects\dem-net\packages
build:
  verbosity: minimal